#pragma once

#include <simgrid/s4u.hpp>
#include <vector>

// Per-host bookkeeping shared by every scheduling policy.
//
// Resource availability (cores/RAM) is tracked here directly by the
// scheduler/simulation code; SimGrid's Energy Plugin separately measures
// the host's actual power draw from the CPU load generated by placed VMs.
// idle_watts/peak_watts are parsed once from the platform's
// "wattage_per_state" property and are needed by the Energy-Aware Best Fit
// policy to project power increases.
struct HostState {
    simgrid::s4u::Host* host = nullptr;

    int  total_cores  = 0;
    int  free_cores   = 0;
    long total_ram_mb = 0;
    long free_ram_mb  = 0;

    double idle_watts = 0.0;
    double peak_watts = 0.0;

    bool   ever_used         = false; // true once >=1 VM has been placed here
    double busy_core_seconds = 0.0;   // time-integral of (cores currently in use)
    double last_update_time  = 0.0;   // sim-time of the last bookkeeping change

    // Power draw (W) implied by `cores_in_use` out of `total_cores`,
    // using the linear model P(u) = idle + (peak - idle) * u.
    double power_at(int cores_in_use) const;

    // Brings the busy-core-time integral up to `now`, then applies the given
    // change in free cores/RAM (negative = placement, positive = release).
    void apply_usage_change(double now, int delta_cores, long delta_ram_mb);
};

// Builds one HostState per host in `engine`, sorted by hostname so the
// rotation/iteration order is deterministic and matches the platform XML
// declaration order (hostA1..hostA6, hostB1..hostB8, hostC1..hostC6).
std::vector<HostState> build_host_states(simgrid::s4u::Engine& engine);
